apiVersion: v1
kind: Namespace
metadata:
  name: nvne
---
apiVersion: v1
kind: Service
metadata:
  name: nvne-espace-collaborateur
  namespace: nvne
  labels:
    app: nvne-espace-collaborateur
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  selector:
    app: nvne-espace-collaborateur
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvne-espace-collaborateur
  namespace: nvne
  labels:
    app: nvne-espace-collaborateur
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nvne-espace-collaborateur
  template:
    metadata:
      labels:
        app: nvne-espace-collaborateur
    spec:
      containers:
      - name: nvne-espace-collaborateur
        image: gcr.io/single-actor-306917/nvne-espace-collaborateur:0.0.1
        ports:
        - name: http
          containerPort: 80
